# How long (in ticks) should the time be between color changes?
# 1 = once per tick
# 20 = once per second
# 1200 = once per minute
#
# Default: 5
armor-speed: 5

# Should disco armor be disabled if a player takes damage?
disable-on-damage: true

menu-title: "&nDisco Armor Menu&r"
display-name: "&1D&2I&3S&4C&5O&r Armor"

lore:
  - "&7This is an awesome armor set,"
  - "&7but you can only remove it by"
  - "&7typing &e/disco-armor off&7."

# Setting a message to "" or '' will prevent it from being sent.
# DO NOT remove any message paths from this config.
messages:
  enable-broadcast: "&b&ki&1&lD&2&lI&3&lS&4&lC&5&lO&b&ki&r"
  disable-broadcast: "&4&l:(&r"
  not-player: "&cOnly players can use this command."
  prevent-click: "&cYou are not allowed to remove your disco armor."
  change-type: "&aYou changed your armor type to &c{type}&a."