# Should the plugin be allowed to check for updates?
update-checker: true

# How long (in ticks) should the time be between color changes?
# 1 = once per tick
# 20 = once per second
# 1200 = once per minute
#
# Default: 5
armor-speed: 5

# Should disco armor be disabled if a player takes damage?
disable-on-damage: true

# Requires 'disable-on-damage: true'
# Should Disco Armor prevent the first hit when a player is wearing disco armor?
prevent-first-hit: true

# Should disco armor have a LUCK enchantment and a HIDE_ENCHANTS flag?
# (This is the default option, players can change their own armor by typing '/disco-armor glow')
glowing: false
