options:
  # The speed that the armor will change colors
  # Examples:
  # 1: Once per tick
  # 20: Once per second
  # 1200: Once per minute
  #
  # Default: 5
  armor speed: 5
  
  # You have many options for disco armor colors
  # Valid Options: 
  #  RANDOM: Random colors on each armor piece
  #  ONE_COLOR: Random colors, but all armor pieces will be the same color
  #  SMOOTH: One color, but the colors will transition smoothly to the next color
  #  OLD_GLORY: Red, White and Blue
  #
  # Default: RANDOM
  armor type: RANDOM
  
# Messages for Disco Armor
# Setting a message to "" will prevent it from sending
messages:
  enabled: "&b&ki&1&lD&2&lI&3&lS&4&lC&5&lO&b&ki"
  disabled: "&4&l:("
  already enabled: "&cYou already have disco armor."
  already disabled: "&cYou already disabled your disco armor."
  invalid usage: "&cInvalid usage! Proper usage is shown below."
  only player: "&cYou are not a Player."
  reloaded: "The config has been reloaded"
  no move: "Do '/discoarmor off' to remove this"
  
  # Do not disable this message, its used to check the armor
  armor display name: "&1D&2I&3S&4C&5O"